import fs from 'node:fs';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
import {zipEntries} from './library.mjs';
export class Projects {
 constructor(library){this.library=library;this.db=library.db;this.dir=path.join(library.dir,'projects');fs.mkdirSync(this.dir,{recursive:true});this.db.exec(`CREATE TABLE IF NOT EXISTS personal_projects(id TEXT PRIMARY KEY,name TEXT NOT NULL,note TEXT NOT NULL,created TEXT NOT NULL);CREATE TABLE IF NOT EXISTS project_files(id TEXT PRIMARY KEY,project TEXT NOT NULL,name TEXT NOT NULL,size INTEGER NOT NULL,kind TEXT NOT NULL);CREATE TABLE IF NOT EXISTS project_slices(project TEXT NOT NULL,file TEXT NOT NULL,PRIMARY KEY(project,file));`);if(!this.db.prepare("PRAGMA table_info(project_files)").all().some(c=>c.name==='slices'))this.db.exec("ALTER TABLE project_files ADD COLUMN slices TEXT NOT NULL DEFAULT '[]'");}
 list(){return this.db.prepare('SELECT * FROM personal_projects ORDER BY name COLLATE NOCASE').all().map(p=>({...p,files:this.db.prepare('SELECT * FROM project_files WHERE project=? ORDER BY name').all(p.id),prints:this.db.prepare('SELECT file FROM project_slices WHERE project=?').all(p.id).map(r=>this.library.get(r.file)).filter(Boolean)}));}
 get(id){return this.list().find(p=>p.id===id);}
 save(id,name,note=''){const clean=String(name||'').trim().slice(0,100);if(!clean)throw Error('Enter a project name');if(id&&!this.get(id))throw Error('Unknown project');const key=id||randomUUID();this.db.prepare('INSERT INTO personal_projects VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,note=excluded.note').run(key,clean,String(note).slice(0,2000),new Date().toISOString());return this.get(key);}
 upload(id,name,buf){if(!this.get(id))throw Error('Unknown project');const clean=path.basename(String(name||'')).replace(/[\u0000-\u001f]/g,'').slice(0,150);const ext=path.extname(clean).toLowerCase();if(!['.stl','.3mf','.obj','.step','.stp','.c4d','.blend','.usdz','.glb','.gltf','.fbx'].includes(ext))throw Error('Choose an STL, 3MF or 3D model file');if(!Buffer.isBuffer(buf)||!buf.length)throw Error('Choose a file');
 let kind=ext==='.stl'?'STL':'3D model',slices=[];
 if(ext==='.3mf'&&[...zipEntries(buf).keys()].some(k=>/^Metadata\/plate_\d+\.gcode$/.test(k))){const prints=this.library.add(clean,buf,'personal',id);for(const f of prints)this.db.prepare('INSERT OR IGNORE INTO project_slices VALUES(?,?)').run(id,f.id);slices=prints.map(f=>f.id);kind='Sliced print';}
 const previous=this.db.prepare('SELECT id FROM project_files WHERE project=? AND name=?').get(id,clean);const key=previous?.id||randomUUID();fs.writeFileSync(path.join(this.dir,key),buf,{mode:0o600});this.db.prepare('INSERT INTO project_files(id,project,name,size,kind,slices) VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET size=excluded.size,kind=excluded.kind,slices=excluded.slices').run(key,id,clean,buf.length,kind,JSON.stringify(slices));return this.get(id);}
 file(project,id){const row=this.db.prepare('SELECT * FROM project_files WHERE project=? AND id=?').get(project,id);if(!row)throw Error('Unknown file');return {...row,path:path.join(this.dir,row.id)};}
 removeFile(project,id){const file=this.file(project,id);fs.rmSync(file.path,{force:true});for(const slice of JSON.parse(file.slices||'[]')){this.library.remove(slice);this.db.prepare('DELETE FROM project_slices WHERE project=? AND file=?').run(project,slice);}this.db.prepare('DELETE FROM project_files WHERE id=?').run(id);}
 remove(id){if(!this.get(id))throw Error('Unknown project');for(const f of this.get(id).files)this.removeFile(id,f.id);for(const r of this.db.prepare('SELECT file FROM project_slices WHERE project=?').all(id))this.library.remove(r.file);this.db.prepare('DELETE FROM project_slices WHERE project=?').run(id);this.db.prepare('DELETE FROM personal_projects WHERE id=?').run(id);}
}
