import {useEffect,useState} from 'react';
import {RefreshCw,Plus,ExternalLink} from 'lucide-react';
import type {Spool} from './live-workspace';
type Offer={id:string;materialId:string;seller:string;label:string;color?:string;url:string;grams:number;price:number;available:boolean|null;refill:boolean;source:string;checked:string;deliverySource?:string;stale:boolean;arrival:string|null;shipping:number|null;delivered:number|null;perKg:number;deliveredPerKg:number|null};
type Material={id:string;name:string;usage:string;url:string;offers:Offer[];error?:string;lastChecked?:string};
type Catalog={materials:Material[];settings:{zip:string;sort:string}};
const names:Record<string,string>={'bambu-tpu-ams':'Bambu TPU for AMS','recreus-conductive':'Recreus Conductive Filaflex','proto-conductive':'Proto-pasta Conductive PLA'};
export const materialName=(id:string)=>names[id]||'Unassigned';
const dollars=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
async function api(url:string,method='GET',body?:unknown):Promise<Catalog>{const r=await fetch(url,{method,...(body!==undefined?{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const b=await r.json();if(!r.ok)throw Error(b.error||'Could not save');return b;}
export function FilamentManager({spools,onSpools,notify,live}:{spools:Spool[];onSpools:(s:Spool[])=>void;notify:(s:string)=>void;live:boolean}){
 const [catalog,setCatalog]=useState<Catalog|null>(null),[busy,setBusy]=useState(false),[add,setAdd]=useState(''),[offerFor,setOfferFor]=useState(''),[quote,setQuote]=useState<Offer|null>(null),[filters,setFilters]=useState<Record<string,string>>({});
 useEffect(()=>{if(!quote)return;const prior=document.activeElement as HTMLElement;const escape=(e:KeyboardEvent)=>{if(e.key==='Escape')setQuote(null);};document.addEventListener('keydown',escape);return ()=>{document.removeEventListener('keydown',escape);prior?.focus();};},[quote]);
 const load=()=>api('/api/materials').then(c=>setCatalog(Array.isArray(c.materials)?c:{materials:[],settings:{zip:'30360',sort:'fastest'}})).catch(e=>notify(e.message));
 useEffect(()=>{load();},[]);
 const save=async(url:string,method:string,body?:unknown)=>{setBusy(true);try{setCatalog(await api(url,method,body));return true;}catch(e){notify((e as Error).message);return false;}finally{setBusy(false);}};
 const spoolForm=(id:string)=><form className="material-form" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget),capacity=Number(d.get('capacity')),remaining=Number(d.get('remaining'));if(remaining>capacity){notify('Remaining grams cannot exceed spool size');return;}onSpools([...spools,{id:crypto.randomUUID(),name:String(d.get('name')),color:String(d.get('color')),materialId:id,capacity,remaining}]);setAdd('');}}><label>Spool name<input name="name" required maxLength={80} placeholder="Black spool"/></label><label>Color<input name="color" type="color" defaultValue="#161d23"/></label><label>Spool size (g)<input name="capacity" type="number" min={100} max={10000} defaultValue={id==='bambu-tpu-ams'?1000:500} required/></label><label>Remaining (g)<input name="remaining" type="number" min={0} max={10000} defaultValue={0} required/></label><button className="primary">Add spool</button><button type="button" className="text-button" onClick={()=>setAdd('')}>Cancel</button></form>;
 return <section className="filament-manager" aria-label="Filament inventory and restock">
 <div className="material-toolbar"><label>Ship to<input aria-label="Delivery ZIP" inputMode="numeric" maxLength={5} defaultValue={catalog?.settings.zip||'30360'} key={catalog?.settings.zip} onBlur={e=>{if(e.target.value!==catalog?.settings.zip)save('/api/materials/settings','PATCH',{zip:e.target.value});}}/></label><select aria-label="Sort restock offers" value={catalog?.settings.sort||'fastest'} onChange={e=>save('/api/materials/settings','PATCH',{sort:e.target.value})}><option value="fastest">Fastest first</option><option value="price">Lowest delivered $/kg</option></select><button className="secondary" disabled={busy} onClick={()=>save('/api/materials/refresh','POST')}><RefreshCw size={16}/> {busy?'Checking…':'Check prices'}</button></div>
 {!live&&<p className="plate-meta">Supplier tracking is available on the hosted app.</p>}
 {!catalog&&<p>Loading…</p>}
 <div className="material-cards">{catalog?.materials.map(m=>{
 const owned=spools.filter(s=>s.materialId===m.id),filter=filters[m.id]||'spools';
 const variant=filters[m.id+'-variant']||'all';
 const offers=m.offers.filter(o=>filter==='all'||filter==='refills'?filter==='all'||o.refill:!o.refill).filter(o=>variant==='all'||`${o.color||'Black'} · ${o.grams} g`===variant);
 return <section className="panel material-card" key={m.id}><div className="section-top"><div><h3>{m.name}</h3><label className="material-usage">Used for<input aria-label={`Usage for ${m.name}`} defaultValue={m.usage} placeholder="Set part usage" onBlur={e=>{if(e.target.value!==m.usage)save('/api/materials/'+m.id,'PATCH',{usage:e.target.value});}}/></label></div><button className="secondary" onClick={()=>setAdd(add===m.id?'':m.id)}><Plus size={16}/> Spool</button></div>
 <div className="material-inventory"><strong>{owned.length ? `${owned.reduce((n,s)=>n+s.remaining,0).toLocaleString()} g remaining · ${owned.length} spools`:'No spools recorded'}</strong>{owned.map(s=><div className="material-spool" key={s.id}><span className="color-dot" style={{background:s.color}}/><span>{s.name}</span><label><input aria-label={`${s.name} remaining grams`} type="number" min={0} max={s.capacity||1000} value={s.remaining} onChange={e=>onSpools(spools.map(x=>x.id===s.id?{...x,remaining:Math.min(s.capacity||1000,Math.max(0,Number(e.target.value)))}:x))}/> g</label><button className="text-button" onClick={()=>{if(confirm(`Remove ${s.name} from inventory?`))onSpools(spools.filter(x=>x.id!==s.id));}}>Remove</button></div>)}</div>
 {add===m.id&&spoolForm(m.id)}
 <div className="restock-heading"><h4>Restock</h4><select aria-label={`Spool format for ${m.name}`} value={filter} onChange={e=>setFilters({...filters,[m.id]:e.target.value})}><option value="spools">Spools</option><option value="refills">Refills</option><option value="all">All formats</option></select><button className="text-button" onClick={()=>setOfferFor(offerFor===m.id?'':m.id)}>Add seller</button></div>
 {m.error&&<p role="alert" className="plate-meta">Price check failed: {m.error}</p>}
 <select className="material-variant" aria-label={`Variant for ${m.name}`} value={variant} onChange={e=>setFilters({...filters,[m.id+'-variant']:e.target.value})}><option value="all">All colors / sizes</option>{[...new Set(m.offers.map(o=>`${o.color||'Black'} · ${o.grams} g`))].map(label=><option key={label}>{label}</option>)}</select>
 <div className="material-offers">{offers.map(o=><article className="material-offer" key={o.id}><div><strong>{o.seller}</strong><small>{o.label.replace(m.name+' - ','')}</small><span className="offer-stock">{o.stale?'Needs price check':o.available===true?'In stock':o.available===false?'Unavailable':'Stock unknown'}</span></div><div className="offer-price"><strong>{dollars(o.price)}</strong><small>{dollars(o.perKg)}/kg before shipping</small><small>{o.deliveredPerKg!==null?`${dollars(o.deliveredPerKg)}/kg ${o.deliverySource==='US estimate'?'US estimate':'delivered'}`:'Shipping unknown'}</small></div><div className="offer-delivery"><strong>{o.arrival?`Arrives ${new Date(o.arrival+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric'})}`:'Arrival unknown'}</strong><small>{o.arrival?o.deliverySource==='US estimate'?'US estimate · confirm at checkout':`Quote for ${catalog.settings.zip}`:'Check at checkout'}</small><button className="text-button" onClick={()=>setQuote(o)}>Set shipping quote</button></div><a className="secondary" href={o.url} target="_blank" rel="noreferrer">Buy <ExternalLink size={14}/></a>{o.source==='manual'&&<button className="text-button" onClick={()=>{if(confirm(`I checked ${o.seller}: ${dollars(o.price)} and stock status are still correct.`))save('/api/material-offers','PATCH',{id:o.id,reconfirm:true});}}>Confirm price / stock</button>}{o.source==='manual'&&<button className="text-button" onClick={()=>save('/api/material-offers/'+o.id,'DELETE')}>Remove seller</button>}</article>)}</div>
 {!offers.length&&<p className="plate-meta">No offers checked yet. <a href={m.url} target="_blank" rel="noreferrer">Open supplier</a></p>}
 <p className="material-checked">{m.lastChecked?`Checked ${new Date(m.lastChecked).toLocaleString()}`:'Not checked'} · Delivery quotes expire after 7 days.</p>
 {offerFor===m.id&&<form className="material-form" onSubmit={async e=>{e.preventDefault();const d=new FormData(e.currentTarget);if(await save('/api/material-offers','POST',{materialId:m.id,seller:d.get('seller'),label:d.get('label'),color:d.get('color'),url:d.get('url'),price:Number(d.get('price')),grams:Number(d.get('grams')),available:d.get('available')==='on',refill:d.get('refill')==='on'}))setOfferFor('');}}><h4>Add exact 1.75 mm material offer</h4><label>Seller<input required name="seller" maxLength={80}/></label><label>Variant / color<input required name="label" maxLength={150}/></label><label>Color<input name="color" defaultValue="Black" maxLength={40} required/></label><label>Product link<input required name="url" type="url"/></label><label>Price (USD)<input required name="price" type="number" min={0.01} step="0.01"/></label><label>Net filament (g)<input required name="grams" type="number" min={100} max={10000}/></label><label className="check-row"><input name="available" type="checkbox" defaultChecked/> In stock</label><label className="check-row"><input name="refill" type="checkbox"/> Refill</label><button className="primary" disabled={busy}>Save seller</button><button className="text-button" type="button" onClick={()=>setOfferFor('')}>Cancel</button></form>}
 </section>;})}</div>
 {spools.some(s=>!s.materialId)&&<section className="panel material-card"><h3>Unassigned spools</h3>{spools.filter(s=>!s.materialId).map(s=><div className="material-spool" key={s.id}><span>{s.name} · {s.remaining} g</span><select aria-label={`Material for ${s.name}`} value="" onChange={e=>onSpools(spools.map(x=>x.id===s.id?{...x,materialId:e.target.value}:x))}><option value="">Choose material</option>{catalog?.materials.map(m=><option value={m.id} key={m.id}>{m.name}</option>)}</select></div>)}</section>}
 {quote&&<div className="modal-backdrop"><form role="dialog" aria-modal="true" aria-label="Shipping quote" onKeyDown={e=>{if(e.key!=='Tab')return;const fields=[...e.currentTarget.querySelectorAll<HTMLElement>('input,button')].filter(x=>!x.hasAttribute('disabled'));if(e.shiftKey&&document.activeElement===fields[0]){e.preventDefault();fields.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===fields.at(-1)){e.preventDefault();fields[0]?.focus();}}} className="panel material-form quote-dialog" onSubmit={async e=>{e.preventDefault();const d=new FormData(e.currentTarget);if(await save('/api/material-offers','PATCH',{id:quote.id,shipping:d.get('shipping'),arrival:d.get('arrival')}))setQuote(null);}}><h3>{quote.seller} · Shipping to {catalog?.settings.zip}</h3><p>{quote.label}</p><label>Shipping cost (USD)<input autoFocus name="shipping" type="number" step="0.01" min={0} defaultValue={quote.shipping??''}/></label><label>Latest estimated arrival<input name="arrival" type="date" min={new Date().toISOString().slice(0,10)} defaultValue={quote.arrival||''}/></label><button className="primary" disabled={busy}>Save quote</button><button className="text-button" type="button" onClick={()=>setQuote(null)}>Cancel</button></form></div>}
 </section>;
}
