import {useEffect,useRef,useState} from 'react';
import {FolderPlus,FileBox,Trash2,Upload,Download} from 'lucide-react';
import {PrintLibrary,type LibraryFile} from './PrintControls';
type Project={id:string;name:string;note:string;files:{id:string;name:string;size:number;kind:string}[];prints:LibraryFile[]};
async function api(url:string,method='GET',body?:unknown){const r=await fetch(url,{method,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d;}
export function PersonalLibrary({notify}:{notify:(s:string)=>void}){
 const [projects,setProjects]=useState<Project[]>([]),[selected,setSelected]=useState<string|null>(null),[editing,setEditing]=useState(false),[name,setName]=useState(''),[note,setNote]=useState(''),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[error,setError]=useState('');const input=useRef<HTMLInputElement>(null);
 const refresh=()=>api('/api/projects').then(p=>{setProjects(p);setLoaded(true);}).catch(e=>{setError(e.message);setLoaded(true);});useEffect(()=>{void refresh();},[]);
 const project=projects.find(p=>p.id===selected);
 const edit=(p?:Project)=>{setName(p?.name||'');setNote(p?.note||'');setEditing(true);};
 const save=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{const p=await api(project?`/api/projects/${project.id}`:'/api/projects',project?'PATCH':'POST',{name,note});await refresh();setSelected(p.id);setEditing(false);}catch(e){notify((e as Error).message);}finally{setBusy(false);}};
 const upload=async(files:FileList|null)=>{if(!project||!files)return;setBusy(true);try{for(const f of Array.from(files)){const r=await fetch(`/api/projects/${project.id}/files`,{method:'POST',headers:{'Content-Type':'application/octet-stream','X-File-Name':encodeURIComponent(f.name)},body:f});const d=await r.json();if(!r.ok)throw Error(d.error||'Upload failed');}notify('Project files uploaded');}catch(e){notify((e as Error).message);}finally{await refresh();setBusy(false);}};
 const remove=async(url:string,message:string)=>{if(!confirm(message))return;try{await api(url,'DELETE');await refresh();if(url===`/api/projects/${selected}`)setSelected(null);}catch(e){notify((e as Error).message);}};
 return <section className="personal-library">
 {!project?<><div className="section-top"><input type="search" aria-label="Search personal projects" placeholder="Search projects…" value={query} onChange={e=>setQuery(e.target.value)}/><button className="primary" onClick={()=>{setSelected(null);edit();}}><FolderPlus size={16}/> New project</button></div>{error&&<p role="alert">{error}</p>}{!loaded?<p>Loading projects…</p>:!projects.length?<div className="empty"><FileBox/><p>Create a project to keep its STLs, 3D models and sliced plates together.</p></div>:<div className="personal-project-grid">{projects.filter(p=>(p.name+' '+p.note).toLowerCase().includes(query.toLowerCase())).map(p=><button className="personal-project-card" key={p.id} onClick={()=>setSelected(p.id)}><FileBox size={30}/><strong>{p.name}</strong><span>{p.files.length} files · {p.prints.length} printable plates</span>{p.note&&<p>{p.note}</p>}</button>)}</div>}</>:<><div className="section-top"><button className="text-button" onClick={()=>setSelected(null)}>← Projects</button><div><button className="secondary" onClick={()=>edit(project)}>Edit project</button><button className="icon-button" aria-label="Delete project" onClick={()=>remove(`/api/projects/${project.id}`,'Delete this project and all its files?')}><Trash2 size={16}/></button></div></div><h2>{project.name}</h2>{project.note&&<p className="plate-meta">{project.note}</p>}<div className="section-top"><h3>Files</h3><button className="secondary" disabled={busy} onClick={()=>input.current?.click()}><Upload size={16}/>{busy?'Uploading…':'Add files'}</button><input ref={input} aria-label="Project files" type="file" multiple hidden accept=".stl,.3mf,.obj,.step,.stp,.c4d,.blend,.usdz,.glb,.gltf,.fbx" onChange={e=>{void upload(e.target.files);e.target.value='';}}/></div><p className="plate-meta">STL, sliced 3MF, or 3D model · up to 95 MB per file. Sliced files become printable plates.</p><ul className="personal-file-list">{project.files.map(f=><li key={f.id}><div><strong>{f.name}</strong><small>{f.kind} · {(f.size/1024/1024).toFixed(1)} MB</small></div><a className="icon-button" href={`/api/projects/${project.id}/files/${f.id}`} aria-label={`Download ${f.name}`}><Download size={16}/></a><button className="icon-button" aria-label={`Remove ${f.name}`} onClick={()=>remove(`/api/projects/${project.id}/files/${f.id}`,`Remove ${f.name}?`)}><Trash2 size={16}/></button></li>)}</ul>{!!project.prints.length&&<PrintLibrary key={project.prints.map(f=>f.id+f.updated).join()} scope="personal" fileIds={project.prints.map(f=>f.id)} title="Printable plates" notify={notify}/>}</>}
 {editing&&<div className="modal-backdrop" onClick={()=>!busy&&setEditing(false)}><form className="plate-assets-editor" role="dialog" aria-modal="true" aria-label={project?'Edit personal project':'New personal project'} onClick={e=>e.stopPropagation()} onSubmit={save}><h3>{project?'Edit project':'New project'}</h3><label>Name<input autoFocus required maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><label>Notes<textarea maxLength={2000} value={note} onChange={e=>setNote(e.target.value)}/></label><div className="watch-actions"><button type="button" className="secondary" disabled={busy} onClick={()=>setEditing(false)}>Cancel</button><button className="primary" disabled={busy}>Save project</button></div></form></div>}
 </section>;
}
